# Generated by Django 3.2.8 on 2021-11-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.userprofile'),
            preserve_default=False,
        ),
    ]
